#!/usr/bin/env bash
#
# nvim-claude-setup.sh
# Installs the nvim-claude Docker image and sets up shell aliases/functions
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_NAME="nvim-claude"
IMAGE_TAG="latest"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Build the Docker image
build_image() {
    log_info "Building Docker image ${IMAGE_NAME}:${IMAGE_TAG}..."

    docker build \
        -t "${IMAGE_NAME}:${IMAGE_TAG}" \
        "${SCRIPT_DIR}"

    log_info "Docker image built successfully!"
}

# Generate the shell function to be sourced
generate_shell_function() {
    cat << 'SHELL_FUNCTION'
# nvim-claude: Run Neovim with Claude Code CLI support in a Docker container
# This function is generated by nvim-claude-setup.sh

nvim-claude() {
    # List of blocked directories (sensitive locations)
    local -a BLOCKED_DIRS=(
        "$HOME"
        "$HOME/.ssh"
        "$HOME/.gnupg"
        "$HOME/.aws"
        "$HOME/.config"
        "$HOME/.local"
        "$HOME/.cache"
        "$HOME/.password-store"
        "$HOME/.mozilla"
        "$HOME/.thunderbird"
        "$HOME/.kube"
        "$HOME/.docker"
        "/etc"
        "/root"
        "/"
    )

    local current_dir
    current_dir="$(pwd)"

    # Resolve to absolute path
    current_dir="$(cd "$current_dir" && pwd -P)"

    # Check if current directory is blocked
    for blocked in "${BLOCKED_DIRS[@]}"; do
        # Resolve blocked path to absolute
        local resolved_blocked
        resolved_blocked="$(cd "$blocked" 2>/dev/null && pwd -P)" || continue

        if [[ "$current_dir" == "$resolved_blocked" ]]; then
            echo "Error: nvim-claude cannot be run from '$blocked' for security reasons."
            echo "Please navigate to a project directory first."
            return 1
        fi
    done

    # Check if we're inside any blocked directory (but not just at it)
    for blocked in "${BLOCKED_DIRS[@]}"; do
        local resolved_blocked
        resolved_blocked="$(cd "$blocked" 2>/dev/null && pwd -P)" || continue

        # Special case: allow subdirectories of $HOME except for sensitive ones
        if [[ "$blocked" == "$HOME" ]]; then
            continue
        fi

        # Check if current_dir starts with blocked path
        if [[ "$current_dir" == "$resolved_blocked"/* ]]; then
            echo "Error: nvim-claude cannot be run from inside '$blocked' for security reasons."
            echo "Please navigate to a project directory first."
            return 1
        fi
    done

    # Determine neovim config and data paths
    local nvim_config="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
    local nvim_data="${XDG_DATA_HOME:-$HOME/.local/share}/nvim"
    local nvim_state="${XDG_STATE_HOME:-$HOME/.local/state}/nvim"
    local nvim_cache="${XDG_CACHE_HOME:-$HOME/.cache}/nvim"
    local claude_config="${HOME}/.claude"
    local supermaven_config="${HOME}/.supermaven"
    local supermaven_data="${XDG_DATA_HOME:-$HOME/.local/share}/supermaven"
    local container_home="${HOME}/.nvim-claude-home"

    # Validate all required directories exist
    if [[ ! -d "$nvim_config" ]]; then
        echo "Error: Neovim config directory not found: $nvim_config"
        return 1
    fi

    if [[ ! -d "$nvim_data" ]]; then
        echo "Error: Neovim data directory not found: $nvim_data"
        return 1
    fi

    if [[ ! -d "$nvim_state" ]]; then
        echo "Error: Neovim state directory not found: $nvim_state"
        return 1
    fi

    if [[ ! -d "$nvim_cache" ]]; then
        echo "Error: Neovim cache directory not found: $nvim_cache"
        return 1
    fi

    if [[ ! -d "$claude_config" ]]; then
        echo "Error: Claude config directory not found: $claude_config"
        echo "Run 'claude' once to initialize it, or create it manually: mkdir -p ~/.claude"
        return 1
    fi

    if [[ ! -d "$supermaven_config" ]]; then
        echo "Error: Supermaven directory not found: $supermaven_config"
        echo "Run neovim once outside the container to initialize Supermaven, or create it manually: mkdir -p ~/.supermaven"
        return 1
    fi

    # Create directories if they don't exist
    mkdir -p "$supermaven_data" 2>/dev/null
    mkdir -p "$container_home" 2>/dev/null

    # Find host neovim installation (required)
    if ! command -v nvim &> /dev/null; then
        echo "Error: Neovim is not installed on the host system."
        echo "nvim-claude requires a host Neovim installation to mount into the container."
        return 1
    fi

    local nvim_path
    nvim_path="$(command -v nvim)"
    # Follow symlinks to get the real path
    nvim_path="$(readlink -f "$nvim_path" 2>/dev/null || realpath "$nvim_path" 2>/dev/null || echo "$nvim_path")"

    # Get the bin directory containing nvim
    local nvim_bin_dir
    nvim_bin_dir="$(dirname "$nvim_path")"

    # Check if it looks like a standard neovim installation (has ../share/nvim)
    local nvim_base_dir
    nvim_base_dir="$(dirname "$nvim_bin_dir")"

    if [[ ! -d "$nvim_base_dir/share/nvim" ]]; then
        echo "Error: Could not find a standard Neovim installation structure."
        echo "Expected to find 'share/nvim' directory at: $nvim_base_dir/share/nvim"
        echo "Neovim path detected: $nvim_path"
        return 1
    fi

    local nvim_host_bin="$nvim_base_dir"

    # Build docker run command
    local -a docker_args=(
        docker run
        --rm
        -it
        --name "nvim-claude-$$"
        # Run as current user for proper file permissions on mounted volumes
        --user "$(id -u):$(id -g)"
        # Set HOME to match mounted structure
        -e HOME=/home/nvimuser
        # Mount container home directory first (base layer)
        -v "${container_home}:/home/nvimuser:rw"
        # Mount host neovim (required)
        -v "${nvim_host_bin}:/host-nvim:ro"
        # Mount neovim config (read-only)
        -v "${nvim_config}:/home/nvimuser/.config/nvim:ro"
        # Mount neovim data (plugins, etc.)
        -v "${nvim_data}:/home/nvimuser/.local/share/nvim:rw"
        # Mount neovim state
        -v "${nvim_state}:/home/nvimuser/.local/state/nvim:rw"
        # Mount neovim cache
        -v "${nvim_cache}:/home/nvimuser/.cache/nvim:rw"
        # Mount current project directory
        -v "${current_dir}:/workspace:rw"
        # Mount Claude config
        -v "${claude_config}:/home/nvimuser/.claude:rw"
        # Mount Supermaven config
        -v "${supermaven_config}:/home/nvimuser/.supermaven:rw"
        # Mount Supermaven data (binary)
        -v "${supermaven_data}:/home/nvimuser/.local/share/supermaven:rw"
        # Set working directory
        -w /workspace
        # Pass through TERM for proper terminal handling
        -e TERM="${TERM:-xterm-256color}"
        # Pass through ANTHROPIC_API_KEY if set
        ${ANTHROPIC_API_KEY:+-e ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}"}
        # Image
        "nvim-claude:latest"
        # Command
        nvim "$@"
    )

    # Run the container
    "${docker_args[@]}"
}

# Completion for nvim-claude (same as nvim)
if type _nvim &>/dev/null; then
    complete -F _nvim nvim-claude
fi
SHELL_FUNCTION
}

# Generate the fish nvim-claude function
generate_fish_nvim_claude() {
    cat << 'FISH_FUNCTION'
# nvim-claude: Run Neovim with Claude Code CLI support in a Docker container
# This function is generated by nvim-claude-setup.sh

function nvim-claude --description "Run Neovim with Claude Code CLI in Docker"
    # List of blocked directories (sensitive locations)
    set -l BLOCKED_DIRS \
        "$HOME" \
        "$HOME/.ssh" \
        "$HOME/.gnupg" \
        "$HOME/.aws" \
        "$HOME/.config" \
        "$HOME/.local" \
        "$HOME/.cache" \
        "$HOME/.password-store" \
        "$HOME/.mozilla" \
        "$HOME/.thunderbird" \
        "$HOME/.kube" \
        "$HOME/.docker" \
        "/etc" \
        "/root" \
        "/"

    set -l current_dir (pwd -P)

    # Check if current directory is blocked
    for blocked in $BLOCKED_DIRS
        # Use realpath instead of cd to avoid changing directory
        set -l resolved_blocked (realpath "$blocked" 2>/dev/null) || continue

        if test "$current_dir" = "$resolved_blocked"
            echo "Error: nvim-claude cannot be run from '$blocked' for security reasons."
            echo "Please navigate to a project directory first."
            return 1
        end
    end

    # Check if we're inside any blocked directory (but not just at it)
    for blocked in $BLOCKED_DIRS
        set -l resolved_blocked (realpath "$blocked" 2>/dev/null) || continue

        # Special case: allow subdirectories of $HOME except for sensitive ones
        if test "$blocked" = "$HOME"
            continue
        end

        # Check if current_dir starts with blocked path
        if string match -q "$resolved_blocked/*" "$current_dir"
            echo "Error: nvim-claude cannot be run from inside '$blocked' for security reasons."
            echo "Please navigate to a project directory first."
            return 1
        end
    end

    # Determine neovim config and data paths
    set -l nvim_config (set -q XDG_CONFIG_HOME && echo $XDG_CONFIG_HOME || echo $HOME/.config)/nvim
    set -l nvim_data (set -q XDG_DATA_HOME && echo $XDG_DATA_HOME || echo $HOME/.local/share)/nvim
    set -l nvim_state (set -q XDG_STATE_HOME && echo $XDG_STATE_HOME || echo $HOME/.local/state)/nvim
    set -l nvim_cache (set -q XDG_CACHE_HOME && echo $XDG_CACHE_HOME || echo $HOME/.cache)/nvim
    set -l claude_config "$HOME/.claude"
    set -l supermaven_config "$HOME/.supermaven"
    set -l supermaven_data (set -q XDG_DATA_HOME && echo $XDG_DATA_HOME || echo $HOME/.local/share)/supermaven
    set -l container_home "$HOME/.nvim-claude-home"

    # Validate all required directories exist
    if not test -d "$nvim_config"
        echo "Error: Neovim config directory not found: $nvim_config"
        return 1
    end

    if not test -d "$nvim_data"
        echo "Error: Neovim data directory not found: $nvim_data"
        return 1
    end

    if not test -d "$nvim_state"
        echo "Error: Neovim state directory not found: $nvim_state"
        return 1
    end

    if not test -d "$nvim_cache"
        echo "Error: Neovim cache directory not found: $nvim_cache"
        return 1
    end

    if not test -d "$claude_config"
        echo "Error: Claude config directory not found: $claude_config"
        echo "Run 'claude' once to initialize it, or create it manually: mkdir -p ~/.claude"
        return 1
    end

    if not test -d "$supermaven_config"
        echo "Error: Supermaven directory not found: $supermaven_config"
        echo "Run neovim once outside the container to initialize Supermaven, or create it manually: mkdir -p ~/.supermaven"
        return 1
    end

    # Create directories if they don't exist
    mkdir -p "$supermaven_data" 2>/dev/null
    mkdir -p "$container_home" 2>/dev/null

    # Find host neovim installation (required)
    if not command -q nvim
        echo "Error: Neovim is not installed on the host system."
        echo "nvim-claude requires a host Neovim installation to mount into the container."
        return 1
    end

    set -l nvim_path (command -v nvim)
    set -l nvim_path (realpath "$nvim_path" 2>/dev/null || echo "$nvim_path")
    set -l nvim_bin_dir (dirname "$nvim_path")
    set -l nvim_base_dir (dirname "$nvim_bin_dir")

    if not test -d "$nvim_base_dir/share/nvim"
        echo "Error: Could not find a standard Neovim installation structure."
        echo "Expected to find 'share/nvim' directory at: $nvim_base_dir/share/nvim"
        echo "Neovim path detected: $nvim_path"
        return 1
    end

    set -l nvim_host_bin "$nvim_base_dir"

    # Build docker run command
    set -l docker_args \
        docker run \
        --rm \
        -it \
        --name "nvim-claude-$fish_pid" \
        --user (id -u):(id -g) \
        -e HOME=/home/nvimuser \
        -v "$container_home:/home/nvimuser:rw" \
        -v "$nvim_host_bin:/host-nvim:ro" \
        -v "$nvim_config:/home/nvimuser/.config/nvim:ro" \
        -v "$nvim_data:/home/nvimuser/.local/share/nvim:rw" \
        -v "$nvim_state:/home/nvimuser/.local/state/nvim:rw" \
        -v "$nvim_cache:/home/nvimuser/.cache/nvim:rw" \
        -v "$current_dir:/workspace:rw" \
        -v "$claude_config:/home/nvimuser/.claude:rw" \
        -v "$supermaven_config:/home/nvimuser/.supermaven:rw" \
        -v "$supermaven_data:/home/nvimuser/.local/share/supermaven:rw" \
        -w /workspace \
        -e TERM=(set -q TERM && echo $TERM || echo xterm-256color)

    # Pass through ANTHROPIC_API_KEY if set
    if set -q ANTHROPIC_API_KEY
        set docker_args $docker_args -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY"
    end

    # Add image and command
    set docker_args $docker_args "nvim-claude:latest" nvim $argv

    # Run the container
    $docker_args
end
FISH_FUNCTION
}

# Install shell function to bash and fish
install_shell_function() {
    # Always install bash function
    local bash_function_file="$HOME/.nvim-claude-function.sh"
    log_info "Writing bash function to ${bash_function_file}..."
    generate_shell_function > "$bash_function_file"

    local bash_rc="$HOME/.bashrc"
    if grep -q "nvim-claude-function.sh" "$bash_rc" 2>/dev/null; then
        log_info "Bash function already sourced in $bash_rc"
    else
        log_info "Adding source line to $bash_rc..."
        echo "" >> "$bash_rc"
        echo "# nvim-claude: Neovim with Claude Code CLI support" >> "$bash_rc"
        echo "[ -f ~/.nvim-claude-function.sh ] && source ~/.nvim-claude-function.sh" >> "$bash_rc"
    fi

    # Always install fish function
    local fish_function_dir="$HOME/.config/fish/functions"
    mkdir -p "$fish_function_dir"

    log_info "Writing fish function to ${fish_function_dir}/nvim-claude.fish..."
    generate_fish_nvim_claude > "$fish_function_dir/nvim-claude.fish"

    log_info "Shell functions installed for bash and fish!"
    log_warn "Please restart your shell to use nvim-claude"
}

# Create necessary directories
create_directories() {
    log_info "Creating necessary directories..."

    mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
    mkdir -p "${XDG_DATA_HOME:-$HOME/.local/share}/nvim"
    mkdir -p "${XDG_STATE_HOME:-$HOME/.local/state}/nvim"
    mkdir -p "${XDG_CACHE_HOME:-$HOME/.cache}/nvim"
    mkdir -p "$HOME/.claude"
    mkdir -p "$HOME/.nvim-claude-home"

    # Add README to container home if it doesn't exist
    if [[ ! -f "$HOME/.nvim-claude-home/README.md" ]]; then
        cat > "$HOME/.nvim-claude-home/README.md" << 'EOF'
# nvim-claude-home

This directory is the container home for `nvim-claude`.

It stores state files that Claude CLI writes to the home directory (like `.claude.json`), which can't be mounted as individual files due to how Docker handles atomic file writes.

Other directories (nvim config, claude credentials, etc.) are mounted on top of this base layer.

**Safe to delete** — it will be recreated automatically. You may need to re-authenticate with Claude.
EOF
    fi

    log_info "Directories created!"
}

# Uninstall shell functions
uninstall_shell_function() {
    log_info "Removing shell functions..."

    # Remove bash function file
    local bash_function_file="$HOME/.nvim-claude-function.sh"
    if [[ -f "$bash_function_file" ]]; then
        rm "$bash_function_file"
        log_info "Removed $bash_function_file"
    fi

    # Remove source line from .bashrc
    local bash_rc="$HOME/.bashrc"
    if [[ -f "$bash_rc" ]] && grep -q "nvim-claude-function.sh" "$bash_rc"; then
        # Remove the comment and source line
        sed -i '/# nvim-claude: Neovim with Claude Code CLI support/d' "$bash_rc"
        sed -i '/nvim-claude-function.sh/d' "$bash_rc"
        log_info "Removed source line from $bash_rc"
    fi

    # Remove fish function file
    local fish_function_file="$HOME/.config/fish/functions/nvim-claude.fish"
    if [[ -f "$fish_function_file" ]]; then
        rm "$fish_function_file"
        log_info "Removed $fish_function_file"
    fi

    # Remove container home directory
    local container_home="$HOME/.nvim-claude-home"
    if [[ -d "$container_home" ]]; then
        rm -rf "$container_home"
        log_info "Removed $container_home"
    fi

    log_info "Shell functions uninstalled!"
    log_warn "Please restart your shell for changes to take effect"
}

# Show usage
show_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --uninstall    Remove shell functions (does not remove Docker image)"
    echo "  --help         Show this help message"
    echo ""
    echo "Without options, installs nvim-claude (builds Docker image and installs shell functions)"
}

# Main installation
main() {
    log_info "=== nvim-claude Setup ==="
    echo ""

    # Check for Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi

    # Check if Docker daemon is running
    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running. Please start Docker first."
        exit 1
    fi

    create_directories
    build_image
    install_shell_function

    echo ""
    log_info "=== Setup Complete ==="
    echo ""
    echo "Usage:"
    echo "  nvim           - Regular Neovim (without Claude)"
    echo "  nvim-claude    - Neovim with Claude Code CLI in Docker container"
    echo ""
    echo "The nvim-claude command will:"
    echo "  - Use your existing Neovim config from ${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
    echo "  - Share plugin cache with your regular Neovim"
    echo "  - Mount the current directory as the project"
    echo "  - Provide access to Claude Code CLI"
    echo ""
    echo "Note: nvim-claude will refuse to run from sensitive directories like \$HOME or ~/.ssh"
    echo ""
}

# Parse arguments and run
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-}" in
        --uninstall)
            uninstall_shell_function
            ;;
        --help|-h)
            show_usage
            ;;
        "")
            main
            ;;
        *)
            log_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
fi
