#!/usr/bin/env bash
#
# mistral-vibe-docker-setup.sh
# Creates the mistral-vibe-docker image and sets up shell aliases/functions

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IMAGE_NAME="mistral-vibe-docker"
IMAGE_TAG="latest"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Build the Docker image
build_image() {
    log_info "Building Docker image ${IMAGE_NAME}:${IMAGE_TAG}..."

    docker build \
		--no-cache \
        -t "${IMAGE_NAME}:${IMAGE_TAG}" \
        "${SCRIPT_DIR}"

    log_info "Docker image built successfully!"
}

# Generate the shell function to be sourced
generate_shell_function() {
    cat << 'SHELL_FUNCTION'
# vibe: Run Mistral Vibe CLI in a Docker container
# This function is generated by mistral-vibe-docker-setup.sh

vibe() {
    # List of blocked directories (sensitive locations)
    local -a BLOCKED_DIRS=(
        "$HOME"
        "$HOME/.ssh"
        "$HOME/.gnupg"
        "$HOME/.aws"
        "$HOME/.config"
        "$HOME/.local"
        "$HOME/.cache"
        "$HOME/.password-store"
        "$HOME/.mozilla"
        "$HOME/.thunderbird"
        "$HOME/.kube"
        "$HOME/.docker"
        "/etc"
        "/root"
        "/"
    )

    local current_dir
    current_dir="$(pwd)"

    # Resolve to absolute path
    current_dir="$(cd "$current_dir" && pwd -P)"

    # Check if current directory is blocked
    for blocked in "${BLOCKED_DIRS[@]}"; do
        # Resolve blocked path to absolute
        local resolved_blocked
        resolved_blocked="$(cd "$blocked" 2>/dev/null && pwd -P)" || continue

        if [[ "$current_dir" == "$resolved_blocked" ]]; then
            echo "Error: vibe cannot be run from '$blocked' for security reasons."
            echo "Please navigate to a project directory first."
            return 1
        fi
    done

    # Check if we're inside any blocked directory (but not just at it)
    for blocked in "${BLOCKED_DIRS[@]}"; do
        local resolved_blocked
        resolved_blocked="$(cd "$blocked" 2>/dev/null && pwd -P)" || continue

        # Special case: allow subdirectories of $HOME except for sensitive ones
        if [[ "$blocked" == "$HOME" ]]; then
            continue
        fi

        # Check if current_dir starts with blocked path
        if [[ "$current_dir" == "$resolved_blocked"/* ]]; then
            echo "Error: vibe cannot be run from inside '$blocked' for security reasons."
            echo "Please navigate to a project directory first."
            return 1
        fi
    done

    # Determine Mistral Vibe config path (now inside container home)
    local container_home="${HOME}/.mistral-vibe-docker-home"
    local vibe_config="${container_home}/.vibe"

    # Create container home if it doesn't exist
    mkdir -p "$container_home" 2>/dev/null

    # Validate Mistral Vibe config exists
    if [[ ! -d "$vibe_config" ]]; then
        log_warn "Mistral Vibe config directory not found: $vibe_config"
        log_info "Creating it now. You'll need to authenticate on first use."
        mkdir -p "$vibe_config"
    fi

    # Build docker run command
    local -a docker_args=(
        docker run
        --rm
        -it
        --name "mistral-vibe-docker-$$"
        # Run as current user for proper file permissions on mounted volumes
        --user "$(id -u):$(id -g)"
        # Set HOME to match mounted structure
        -e HOME=/home/vibeuser
        # Mount container home directory (includes .vibe config)
        -v "${container_home}:/home/vibeuser:rw"
        # Mount current project directory
        -v "${current_dir}:/workspace:rw"
        # Set working directory
        -w /workspace
        # Pass through TERM for proper terminal handling
        -e TERM="${TERM:-xterm-256color}"
        # Pass through MISTRAL_API_KEY if set
        ${MISTRAL_API_KEY:+-e MISTRAL_API_KEY="${MISTRAL_API_KEY}"}
        # Image
        "mistral-vibe-docker:latest"
        # Command - if no args, run vibe; otherwise pass through to bash
        ${@:+bash -c "vibe $*"}
    )

    # If no arguments, run vibe interactively
    if [[ $# -eq 0 ]]; then
        docker_args+=("vibe")
    fi

    # Run the container
    "${docker_args[@]}"
}
SHELL_FUNCTION
}

# Generate the fish mistral function
generate_fish_vibe() {
    cat << 'FISH_FUNCTION'
# vibe: Run Mistral Vibe CLI in a Docker container
# This function is generated by mistral-vibe-docker-setup.sh

function vibe --description "Run Mistral Vibe CLI in Docker"
    # List of blocked directories (sensitive locations)
    set -l BLOCKED_DIRS \
        "$HOME" \
        "$HOME/.ssh" \
        "$HOME/.gnupg" \
        "$HOME/.aws" \
        "$HOME/.config" \
        "$HOME/.local" \
        "$HOME/.cache" \
        "$HOME/.password-store" \
        "$HOME/.mozilla" \
        "$HOME/.thunderbird" \
        "$HOME/.kube" \
        "$HOME/.docker" \
        "/etc" \
        "/root" \
        "/"

    set -l current_dir (pwd -P)

    # Check if current directory is blocked
    for blocked in $BLOCKED_DIRS
        # Use realpath instead of cd to avoid changing directory
        set -l resolved_blocked (realpath "$blocked" 2>/dev/null) || continue

        if test "$current_dir" = "$resolved_blocked"
            echo "Error: vibe cannot be run from '$blocked' for security reasons."
            echo "Please navigate to a project directory first."
            return 1
        end
    end

    # Check if we're inside any blocked directory (but not just at it)
    for blocked in $BLOCKED_DIRS
        set -l resolved_blocked (realpath "$blocked" 2>/dev/null) || continue

        # Special case: allow subdirectories of $HOME except for sensitive ones
        if test "$blocked" = "$HOME"
            continue
        end

        # Check if current_dir starts with blocked path
        if string match -q "$resolved_blocked/*" "$current_dir"
            echo "Error: vibe cannot be run from inside '$blocked' for security reasons."
            echo "Please navigate to a project directory first."
            return 1
        end
    end

    # Determine Mistral Vibe config path (now inside container home)
    set -l container_home "$HOME/.mistral-vibe-docker-home"
    set -l vibe_config "$container_home/.vibe"

    # Create container home if it doesn't exist
    mkdir -p "$container_home" 2>/dev/null

    # Validate Mistral Vibe config exists
    if not test -d "$vibe_config"
        echo "Warning: Mistral Vibe config directory not found: $vibe_config"
        echo "Creating it now. You'll need to authenticate on first use."
        mkdir -p "$vibe_config"
    end

    # Build docker run command
    set -l docker_args \
        docker run \
        --rm \
        -it \
        --name "mistral-vibe-docker-$fish_pid" \
        --user (id -u):(id -g) \
        -e HOME=/home/vibeuser \
        -v "$container_home:/home/vibeuser:rw" \
        -v "$current_dir:/workspace:rw" \
        -w /workspace \
        -e TERM=(set -q TERM && echo $TERM || echo xterm-256color)

    # Pass through MISTRAL_API_KEY if set
    if set -q MISTRAL_API_KEY
        set docker_args $docker_args -e MISTRAL_API_KEY="$MISTRAL_API_KEY"
    end

    # Add image
    set docker_args $docker_args "mistral-vibe-docker:latest"

    # Add command - if args provided, pass to bash; otherwise run vibe
    if test (count $argv) -gt 0
        set docker_args $docker_args bash -c "vibe $argv"
    else
        set docker_args $docker_args vibe
    end

    # Run the container
    $docker_args
end
FISH_FUNCTION
}

# Install shell function to bash and fish
install_shell_function() {
    # Always install bash function
    local bash_function_file="$HOME/.mistral-vibe-docker-function.sh"
    log_info "Writing bash function to ${bash_function_file}..."
    generate_shell_function > "$bash_function_file"

    local bash_rc="$HOME/.bashrc"
    if grep -q "mistral-vibe-docker-function.sh" "$bash_rc" 2>/dev/null; then
        log_info "Bash function already sourced in $bash_rc"
    else
        log_info "Adding source line to $bash_rc..."
        echo "" >> "$bash_rc"
        echo "# mistral-vibe-docker: Mistral Vibe CLI in Docker sandbox" >> "$bash_rc"
        echo "[ -f ~/.mistral-vibe-docker-function.sh ] && source ~/.mistral-vibe-docker-function.sh" >> "$bash_rc"
    fi

    # Always install fish function
    local fish_function_dir="$HOME/.config/fish/functions"
    mkdir -p "$fish_function_dir"

    log_info "Writing fish function to ${fish_function_dir}/vibe.fish..."
    generate_fish_vibe > "$fish_function_dir/vibe.fish"

    log_info "Shell functions installed for bash and fish!"
    log_warn "Please restart your shell to use the 'vibe' command"
}

# Create necessary directories
create_directories() {
    log_info "Creating necessary directories..."

    mkdir -p "$HOME/.mistral-vibe-docker-home/.vibe"

	ln -s /opt/vibeuser-local/ $HOME/.mistral-vibe-docker-home/.local &> /dev/null || true

    # Add README to container home if it doesn't exist
    if [[ ! -f "$HOME/.mistral-vibe-docker-home/README.md" ]]; then
        cat > "$HOME/.mistral-vibe-docker-home/README.md" << 'EOF'
# mistral-vibe-docker-home

This directory is the container home for `vibe` (Docker version).

It contains:
- `.vibe/` - Mistral Vibe CLI configuration and authentication
- Other state files that Mistral Vibe CLI writes to the home directory

**Safe to delete** — it will be recreated automatically. You may need to re-authenticate with Mistral.
EOF
    fi

    log_info "Directories created!"
}

# Uninstall shell functions
uninstall_shell_function() {
    log_info "Removing shell functions..."

    # Remove bash function file
    local bash_function_file="$HOME/.mistral-docker-function.sh"
    if [[ -f "$bash_function_file" ]]; then
        rm "$bash_function_file"
        log_info "Removed $bash_function_file"
    fi

    # Remove source line from .bashrc
    local bash_rc="$HOME/.bashrc"
    if [[ -f "$bash_rc" ]] && grep -q "mistral-docker-function.sh" "$bash_rc"; then
        # Remove the comment and source line
        sed -i '/# mistral-docker: Mistral Vibe CLI in Docker sandbox/d' "$bash_rc"
        sed -i '/mistral-docker-function.sh/d' "$bash_rc"
        log_info "Removed source line from $bash_rc"
    fi

    # Remove fish function file
    local fish_function_file="$HOME/.config/fish/functions/vibe.fish"
    if [[ -f "$fish_function_file" ]]; then
        rm "$fish_function_file"
        log_info "Removed $fish_function_file"
    fi

    # Remove container home directory
    local container_home="$HOME/.mistral-vibe-docker-home"
    if [[ -d "$container_home" ]]; then
        rm -rf "$container_home"
        log_info "Removed $container_home"
    fi

    log_info "Shell functions uninstalled!"
    log_warn "Please restart your shell for changes to take effect"
}

# Show usage
show_usage() {
    echo "Usage: $0 [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --uninstall    Remove shell functions (does not remove Docker image)"
    echo "  --help         Show this help message"
    echo ""
    echo "Without options, installs mistral-vibe-docker (builds Docker image and installs shell functions)"
}

# Main installation
main() {
    log_info "=== mistral-vibe-docker Setup ==="
    echo ""

    # Check for Docker
    if ! command -v docker &> /dev/null; then
        log_error "Docker is not installed. Please install Docker first."
        exit 1
    fi

    # Check if Docker daemon is running
    if ! docker info &> /dev/null; then
        log_error "Docker daemon is not running. Please start Docker first."
        exit 1
    fi

    create_directories
    build_image
    install_shell_function

    echo ""
    log_info "=== Setup Complete ==="
    echo ""
    echo "Usage:"
    echo "  vibe        - Run Mistral Vibe CLI in Docker container"
    echo ""
    echo "The vibe command will:"
    echo "  - Run in a sandboxed Docker environment"
    echo "  - Mount the current directory as the project"
    echo "  - Use your Mistral Vibe configuration from ~/.mistral-vibe-docker-home/.vibe"
    echo ""
    echo "Note: vibe will refuse to run from sensitive directories like \$HOME or ~/.ssh"
    echo ""
}

# Parse arguments and run
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    case "${1:-}" in
        --uninstall)
            uninstall_shell_function
            ;;
        --help|-h)
            show_usage
            ;;
        "")
            main
            ;;
        *)
            log_error "Unknown option: $1"
            show_usage
            exit 1
            ;;
    esac
fi
